version: '3.8'

services:
  tts-reader:
    build: .
    ports:
      - "2022:2022"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped